services:
- docker
install:
- docker build -t arpaesimc:${DOCKER_IMAGE/:/-} ${DOCKER_IMAGE/:/-}
env:
- DOCKER_IMAGE=centos:7
- DOCKER_IMAGE=rockylinux:8
- DOCKER_IMAGE=fedora:31
- DOCKER_IMAGE=fedora:32
- DOCKER_IMAGE=fedora:33
- DOCKER_IMAGE=fedora:rawhide
matrix:
  allow_failures:
  - env: DOCKER_IMAGE=fedora:rawhide
script:
- docker run arpaesimc:${DOCKER_IMAGE/:/-} /bin/bash -c "arki-query --version"
