services:
- docker
install:
- docker build -t arpaesimc:$IMAGE $IMAGE
env:
- DOCKER_IMAGE=fedora:30
- IMAGE=centos-7
- IMAGE=centos-8
- IMAGE=fedora-30
- IMAGE=fedora-31
- IMAGE=fedora-32
- IMAGE=fedora-rawhide
matrix:
  allow_failures:
  - env: IMAGE=fedora-rawhide
script:
- docker run arpaesimc:$IMAGE /bin/bash -c "arki-query --version"
