services:
    - docker

install:
    - docker build -t arpaesimc:$IMAGE $IMAGE

env:
    - IMAGE=centos-7
    - IMAGE=fedora-27
    - IMAGE=fedora-28
    - IMAGE=fedora-29
    - IMAGE=fedora-30
    - IMAGE=fedora-31
    - IMAGE=fedora-32
    - IMAGE=fedora-rawhide

script:
    - docker run arpaesimc:$IMAGE /bin/bash -c "arki-query --version"
